### PR TITLE
Pass message thread id to reply to the correct thread

### PR DESCRIPTION
**Pull request by v1ctor**
# Summary
This is done similar way to the [python-telegram-bot](https://github.com/python-telegram-bot/python-telegram-bot/blob/422993b8ab05d49dd49ab58c500f880918d894a7/telegram/_forumtopic.py#L31)

This is needed so bot can reply to a specific reply thread or a specific topic in a supergroup.

# Test
To be able to echo messages to a specific thread you have to enable Business Mode so Bot can read messages:
Screenshot 2024-07-17 at 19 08 45

It looks like this:
https://github.com/user-attachments/assets/a327b8a8-5fc0-4354-ad1b-a60b9afabd62

# As per contribution guidelines
```> Task :ktlintFormat
19:17:06.968 [main] WARN com.pinterest.ktlint.internal.KtlintCommandLine - No files matched [src/**/*.kt]

BUILD SUCCESSFUL in 5s
6 actionable tasks: 6 executed

> Task :ktlint
19:17:27.084 [main] WARN com.pinterest.ktlint.internal.KtlintCommandLine - No files matched [src/**/*.kt]

> Task :telegram:test

SendDocumentIT > #sendDocument using all params with document file creates request correctly() FAILED
    junit.framework.ComparisonFailure at SendDocumentIT.kt:85
    
BUILD FAILED in 8s
15 actionable tasks: 7 executed, 8 up-to-date
```
One test is failing but it also fails in `main`

### CODE REVIEW

**Comment by v1ctor** [comment]
@red-avtovo Hi, I saw that you were the last to approve PR, can you please review this? 

I've seen that there weren't any version in half a year, how is the process of new version releasing look like?

**Comment by v1ctor** [comment]
Thank you @red-avtovo! Please tell me if you need any help. 🙌

**Comment by v1ctor** [comment]
Hey @red-avtovo do you want any help with releasing/maintaining this library? I would like to offer my help if you have any space for new people.

**Comment by red-avtovo** [comment]
Sorry, had no time this week. Will try to release this weekend

**Pull request merged**
