### PR TITLE
Fix mapToTelegramBotResult function

### PR DESCRIPTION
**Pull request by Zheg-al**
Fix bug in mapping api request result.
Telegram responds on error with same HTTP code as "error_code" field inside body, not with the 200 - Success,
image

### CODE REVIEW

**Comment by red-avtovo** [comment]
@Zheg-al could you please resolve conflicts?

**Comment by Zheg-al** [comment]
@red-avtovo, resolved the conflicts

**Comment by red-avtovo** [comment]
the CI failed on linting

**Comment by Zheg-al** [comment]
> the CI failed on linting

Yeah, sorry. Fixed it.

**Comment by red-avtovo** [comment]
Thanks!

**Pull request merged**
