### PR TITLE
GH-323 expose secret token for the webhook configuration

### PR DESCRIPTION
**Pull request by artemptushkin**
Leveraging `secret_token` property of the method [here](https://core.telegram.org/bots/api#setwebhook)

### CODE REVIEW

**Review by red-avtovo — APPROVED** [review]
Nice one!

**Comment by red-avtovo** [comment]
Could you please resolve conflicts and then I'm more than happy to merge your changes

**Comment by artemptushkin** [comment]
> Could you please resolve conflicts and then I'm more than happy to merge your changes

updated, ty

**Review by red-avtovo — APPROVED** [review]

**Comment by red-avtovo** [comment]
Oddly enough, the CI went to sleep. I will close and reopen the PR to trigger the CI once more

**Comment by red-avtovo** [comment]
Thanks for the change @artemptushkin!

**Pull request merged**
