### PR TITLE
Use `Channel` instead of `BlockingQueue`

### PR DESCRIPTION
**Pull request by JcMinarro**
Use `Channel` instead of `BlockingQueue` as was suggested [here](https://github.com/kotlin-telegram-bot/kotlin-telegram-bot/pull/277#discussion_r1125709275)

This PR depend on #277

### CODE REVIEW

**Review by vjgarciag96 — APPROVED** [review]
Nice one! It's cool to see how clean migrating between these 2 is (at least in this case). We can merge after we get the other one in. Thanks for the nice work!

**Comment by JcMinarro** [comment]
> Nice one! It's cool to see how clean migrating between these 2 is (at least in this case). We can merge after we get the other one in. Thanks for the nice work!

Ok, the previous one is already merged.
I have updated it to avoid conflict.
Reviewing it now should be easier, as only "Channel Changes" are on it.
Let me know if it is fine to be merged

**Comment by JcMinarro** [comment]
Any chance to merge it?

**Review by vjgarciag96 — APPROVED** [review]
LGTM. I'm very sorry for the big delay in reviewing and merging this.

**Pull request merged**
