### PR TITLE
Support 'Login Url' payload for InlineKeyboardButton

### PR DESCRIPTION
**Pull request by alexdavliatov**

### CODE REVIEW

**Comment by icypig** [comment]
When will this be merged?

**Comment by icypig** [comment]
@alexdavliatov Hi, sry to bother here, do we have any plan to merge this PR?

**Comment by alexdavliatov** [comment]
> @alexdavliatov Hi, sry to bother here, do we have any plan to merge this PR?

Hi! I think this question should be addressed to the maintainer. Without approve I can not merge this request

**Comment by icypig** [comment]
@vjgarciag96 hi, sry to bother here, could we consider to approve this PR, i think it's add a great feature here

**Review by red-avtovo — APPROVED** [review]

**Comment by alexdavliatov** [comment]
@red-avtovo could you merge this PR please?

**Comment by red-avtovo** [comment]
I actually came here to try, but unfortunately I don't have permissions, sorry. Let me try to request those

**Comment by icypig** [comment]
Hi bro, any update about this PR?

**Comment by red-avtovo** [comment]
I was just promoted, so I'm happy to merge it

**Comment by icypig** [comment]
Hi, could we release this feature?

**Pull request merged**
