### PR TITLE
Handlers to functions with receiver without proxy

### PR DESCRIPTION
**Pull request by reopold**
Hello.
I modified **vjgarciag96** branch handlers-to-functions-with-receiver.
Handlers to functions with receiver #96 can be implemented a little easier, without a proxy.
Please take a look.
Don't kick me too hard, this is my first experience on github and writing in Kotlin.

_P.S.: I didn't even need to add HandlerEnvironment, but I need it for the next PR(chain of steps)._
Thanks.

### CODE REVIEW

**Comment by seik** [comment]
Hi @reopold, why did you close this PR?

I currently reviewed #103 and If there is something we can add to that PR or way to improve it I'm open to hear that.

**Comment by reopold** [comment]
Sorry, this is my first experience on github.
I first made PR, and then I saw that I have not all the tests pass. 
I'm trying to fix the tests.
Also, I do not know how better to do this PR. 
I continued **vjgarciag96** branch.  I rewrote his code.
What should I do?
Make a PR to his repository?
Or make a PR here that includes all his commits?

**Comment by seik** [comment]
Since @vjgarciag96 did an incredible job doing that PR I would feel bad merging this. 

Let's do what you are saying, create a PR on @vjgarciag96 repo on the same branch he is doing the PR here, review the changes with him and then after reviewing that we will merge his PR here.

I feel this way is the most fair.

**Comment by vjgarciag96** [comment]
@seik: I'd say these are two different things, so we can easily split them in different PRs.

My PR is about changing our updates handling functions to now implicitly have access to the updates' arguments in the context of the function instead of having to explicitly indicate them (and also bringing better type support for those arguments).
 
However, my PR doesn't include any change to the `Handler` class and doesn't use a different pattern we weren't using before (we use the proxy pattern we'd been using in other handlers)

The PR of @reopold is mostly about reworking how handlers are implemented. The PR includes changes to the `Handler` class to add a new method and also changes all of the implemented handlers to get rid of the proxies we were using before.

IMO we could merge the first PR, and once merged, we can cherrypick the changes proposed here to a new branch checked out from main/master. Then, we could review and discuss the new changes in an easier and clearer way, and the risks would be lower.

What are your thoughts?

**Comment by reopold** [comment]
I agree with @vjgarciag96. 
I will wait for the merge of his branch, and then suggest my PR to improve the implementation.
This will be more consistent.

**Comment by seik** [comment]
Much better approach. Thank you all!

**Pull request closed without merging**
